server:
  port: 8088
spring:
  application:
    name: rims
  cloud:
    sentinel:
      transport:
        #Sentinel控制台地址
        dashboard: 127.0.0.1:8858
#        eager: true
        #当前服务的ip
#        clientIp: 127.0.0.1
        port: 8719
  jackson:
    property-naming-strategy: SNAKE_CASE
